name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.x']
        platform: [linux-amd64, windows-amd64, darwin-amd64, darwin-arm64]
        include:
          - platform: linux-amd64
            os: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
            binary_name: databricks-mcp
            asset_name: databricks-mcp-linux-amd64
          - platform: windows-amd64
            os: ubuntu-latest
            GOOS: windows
            GOARCH: amd64
            binary_name: databricks-mcp.exe
            asset_name: databricks-mcp-windows-amd64.exe
          - platform: darwin-amd64
            os: ubuntu-latest
            GOOS: darwin
            GOARCH: amd64
            binary_name: databricks-mcp
            asset_name: databricks-mcp-darwin-amd64
          - platform: darwin-arm64
            os: ubuntu-latest
            GOOS: darwin
            GOARCH: arm64
            binary_name: databricks-mcp
            asset_name: databricks-mcp-darwin-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Get version from tag
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          # For non-tag builds, try to get the latest tag or use version from version.go if no tags exist
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LATEST_TAG" ]; then
            # Extract version from version.go if no tags exist
            VERSION=$(grep -oP 'Version = "\K[^"]+' version.go || echo "0.0.0")
            VERSION="$VERSION-dev-$(git rev-parse --short HEAD)"
          else
            VERSION="${LATEST_TAG#v}-dev-$(git rev-parse --short HEAD)"
          fi
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
      run: |
        go build -trimpath -ldflags="-s -w -X 'main.Version=${{ env.VERSION }}' -X 'main.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)' -X 'main.GitCommit=$(git rev-parse --short HEAD)'" -o ${{ matrix.binary_name }}

    - name: Install UPX
      if: matrix.GOOS != 'darwin'
      run: |
        sudo apt-get update
        sudo apt-get install -y upx-ucl

    - name: Compress binary with UPX
      if: matrix.GOOS != 'darwin'
      run: |
        upx --best --lzma ${{ matrix.binary_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.binary_name }}

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        run: |
          # Get the current tag
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          echo "Current tag: $CURRENT_TAG"

          # Check if this is the first tag
          TAG_COUNT=$(git tag | wc -l)

          if [ "$TAG_COUNT" -le 1 ]; then
            # This is the first tag or there's only one tag (the current one)
            echo "This is the first release. Including all commits."
            # Get all commits up to the current tag
            CHANGELOG=$(git log --pretty=format:"* %s (%h)" $CURRENT_TAG)

            # If the changelog is empty (can happen with the first tag), get all commits
            if [ -z "$CHANGELOG" ]; then
              echo "Getting all commits for the first release."
              CHANGELOG=$(git log --pretty=format:"* %s (%h)")
            fi
          else
            # Try to get the previous tag
            PREVIOUS_TAG=$(git describe --tags --abbrev=0 $CURRENT_TAG^ 2>/dev/null || echo "")

            if [ -z "$PREVIOUS_TAG" ]; then
              # If we can't get the previous tag, get all commits up to the current tag
              echo "No previous tag found. Using all commits up to $CURRENT_TAG."
              CHANGELOG=$(git log --pretty=format:"* %s (%h)" $CURRENT_TAG)
            else
              echo "Previous tag: $PREVIOUS_TAG"
              # Get commits between the previous tag and the current tag
              CHANGELOG=$(git log --pretty=format:"* %s (%h)" $PREVIOUS_TAG..$CURRENT_TAG)
            fi
          fi

          # Save changelog to output
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            # Release ${{ github.ref_name }} of databricks-mcp

            ## Changelog
            ${{ env.CHANGELOG }}
          draft: false
          prerelease: false

      - name: Upload Linux AMD64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/databricks-mcp-linux-amd64/databricks-mcp
          asset_name: databricks-mcp-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows AMD64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/databricks-mcp-windows-amd64.exe/databricks-mcp.exe
          asset_name: databricks-mcp-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Darwin AMD64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/databricks-mcp-darwin-amd64/databricks-mcp
          asset_name: databricks-mcp-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Darwin ARM64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/databricks-mcp-darwin-arm64/databricks-mcp
          asset_name: databricks-mcp-darwin-arm64
          asset_content_type: application/octet-stream
